from pathlib import Path
# -*- coding: utf-8 -*-
import json

# Depo koku - kisisel makine yolu yerine bu dosyanin konumundan turetilir.
KOK = Path(__file__).resolve().parents[1]

rows = [
{"soru": "ADR (Architecture Decision Record) nedir ve neden sadece kararı değil, gerekçesini de içermelidir?",
"cevap": "ADR, bir mimari kararın ne olduğunu, neden alındığını, hangi alternatiflerin değerlendirildiğini ve hangi sonuçları doğurduğunu kaydeden kısa ve yapılandırılmış bir belgedir. Genellikle Title, Status (Proposed, Accepted, Deprecated, Superseded), Context, Decision ve Consequences bölümlerinden oluşur. ADR'nin sadece gerekçe içermesi zorunludur çünkü kod, ne yaptığını gösterir ama neden o şekilde yapıldığını göstermez. Bir yıl sonra sisteme bakan bir mühendis, örneğin neden ORM yerine raw SQL kullanıldığını kod içinde bulamaz; bu bilgi ADR olmadan ya kaybolur ya da sözlü aktarımla (tribal knowledge) bozularak dolaşır. Sadece 'Kafka kullanacağız' yazıp RabbitMQ veya SQS'in neden elendiğini belirtmemek, ADR'nin asıl değerini, yani gelecekte kararın sorgulanabilir olmasını yok eder. Aynı şekilde Consequences bölümünü boş bırakmak, kararın operasyonel karmaşıklık veya vendor lock-in gibi olumsuz taraflarını gizler ve kararı olduğundan daha temiz gösterir. Bu yüzden iyi bir ADR, kararın alındığı anın bağlamını bütün detaylarıyla dondurmalıdır.",
"kaynak": "", "alan": ""},

{"soru": "ADR'ler neden immutable (değiştirilemez) olarak ele alınır, bir karar değiştiğinde ne yapılır?",
"cevap": "ADR'ler immutable kabul edilir çünkü amaçları kararların tarihsel bir izini (audit trail) oluşturmaktır: kim, ne zaman, hangi bağlamda ne düşünmüş, bu bilginin kaybolmaması gerekir. Bir karar zamanla değiştiğinde eski ADR düzenlenmez ya da üzerine yazılmaz; bunun yerine yeni bir ADR yazılır ve eski ADR 'Superseded by ADR-XXX' şeklinde işaretlenir. Eski ADR'yi silmek veya güncellemek, o kararın alındığı andaki kısıtların ve alternatiflerin bilgisini yok eder, oysa bu bilgi gelecekte 'o zamanki kısıtlar hala geçerli mi' sorusunu cevaplamak için değerlidir. ADR'ler kod deposu içinde (örneğin docs/adr/ klasöründe) numaralandırılarak tutulur ve pull request süreciyle gözden geçirilir, böylece kararlar da kod gibi takım tarafından tartışılıp onaylanır. Yaygın bir hata, mimari kökten değiştiğinde eski ADR'nin superseded olarak işaretlenmemesidir; bu durumda yeni katılan biri güncelliğini yitirmiş bir kararı hala geçerliymiş gibi okuyabilir ve yanlış varsayımlarla ilerleyebilir.",
"kaynak": "", "alan": ""},

{"soru": "Her küçük teknik karar için ADR yazmak mantıklı mı, hangi eşik kullanılmalı?",
"cevap": "Hayır, her küçük teknik seçim için ADR yazmak önerilmez. ADR, geri dönüşü maliyetli (expensive to reverse), birden fazla ekibi etkileyen veya uzun vadeli sonuçları olan kararlar için yazılmalıdır. Örneğin bir değişken adı seçimi ADR gerektirmezken, bir veritabanı motoru seçimi gerektirir. Bu eşiği doğru belirlemek önemlidir çünkü iki uçta da risk vardır: her şey için ADR yazmak 'ADR yorgunluğu' yaratır ve zamanla takımın pratiği tamamen terk etmesine yol açar; hiçbir şey için ADR yazmamak ise dokümantasyon mühendisliğinin çözmeye çalıştığı orijinal problemi, yani kararların gerekçesinin unutulmasını geri getirir. Ayrıca ADR'yi karar alındıktan aylar sonra yazmaya çalışmak da bir tuzaktır, çünkü o andaki kısıtlar ve değerlendirilen alternatifler zamanla unutulur ve yazılan belge düşük kaliteli olur. Bu nedenle ADR yazma işlemi, karar alma sürecinin sonradan eklenen bir formalite değil, doğal bir parçası olmalıdır.",
"kaynak": "", "alan": ""},

{"soru": "Doc drift nedir ve otomatik API referans üretimi bu sorunu nasıl çözer?",
"cevap": "Doc drift, kod ile onu anlatan dokümantasyonun zamanla birbirinden sapması, yani kod değiştikçe elle yazılmış dokümantasyonun eskimesi durumudur. Kök neden, kod ve dokümantasyonun iki ayrı artefakt olarak senkron tutulmaya çalışılmasıdır; bu, insan disiplinine bağımlı bir süreç yaratır ve insan disiplini ölçeklenmez. Çözüm, dokümantasyonu kodun kendisinden türetmektir (generate from source). Bunun iki yolu vardır: şema-öncelikli (schema-first) yaklaşımda OpenAPI şeması yazılır ve hem sunucu kodu hem istemci SDK'si hem dokümantasyon bu şemadan üretilir; kod-öncelikli (code-first) yaklaşımda ise API kodu tip bilgisi ve annotation/decorator'larla işaretlenir (örneğin FastAPI'de Python type hint'leri) ve bir araç bu kodu tarayarak OpenAPI şemasını otomatik üretir. Her iki yöntemde de ortak nokta, dokümantasyonun elle senkronize edilen ayrı bir dosya değil, derleme/build zincirinin bir çıktısı olmasıdır. Şema doğrulaması genellikle CI'da otomatik çalıştırılır, böylece uyumsuz bir değişiklik merge edilmeden önce yakalanır.",
"kaynak": "", "alan": ""},

{"soru": "Otomatik üretilen API dokümantasyonunda hangi yaygın hatalar yapılır?",
"cevap": "Üç yaygın hata öne çıkar. Birincisi, şema-first yaklaşım yerine koddan bağımsız elle yazılmış bir OpenAPI dosyası tutmaya çalışmaktır; bu, zamanla gerçek API davranışından sapar ve otomatik üretimin çözmeye çalıştığı tam problemi geri getirir. İkincisi, sadece 'happy path'i dokümante etmektir: hata durumları, rate-limit yanıtları ve sayfalama (pagination) davranışı gibi mutlu yol dışı senaryolar genellikle atlanır, oysa API tüketicisinin en çok ihtiyaç duyduğu bilgi çoğunlukla budur. Üçüncüsü, iç detayları dışa sızdırmaktır; otomatik üretim bazen iç veri modelini (internal DTO) doğrudan dışa yansıtabilir, bu hem güvenlik hem API tasarım sağlığı açısından risklidir. Doğru yaklaşım, dış API sözleşmesini iç uygulamadan kasıtlı olarak ayrıştırmak, yani API şemasını doğrudan içerideki koddan değil, özel tasarlanmış bir sözleşme katmanından türetmektir. Ayrıca şema CI'da doğrulanmalı ve breaking-change tespiti (alan kaldırma, tip değişikliği gibi) PR aşamasında otomatik yapılmalıdır.",
"kaynak": "", "alan": ""},

{"soru": "Docs-as-code yaklaşımı ile geleneksel wiki tabanlı dokümantasyon arasındaki fark nedir?",
"cevap": "Docs-as-code, dokümantasyonun kod ile aynı araçlarla ve aynı süreçlerle yönetilmesi felsefesidir: düz metin formatında (Markdown, reStructuredText, AsciiDoc) yazılır, Git gibi bir sürüm kontrol sisteminde kodla aynı veya yakın bağlı bir depoda tutulur, pull request/code review süreciyle değişir, CI/CD ile statik site üreticileri (MkDocs, Docusaurus, Sphinx) aracılığıyla derlenip yayınlanır ve linting ile otomatik testlerden geçer. Buna karşılık bir wiki veya paylaşılan Word dosyası, kod değişikliğinden farklı zaman diliminde, farklı kişiler tarafından, farklı onay süreçleriyle güncellenir; bu ayrışma doc drift'in temel nedenidir. Docs-as-code, dokümantasyonu kodun yanına koyarak aynı commit'te, aynı PR'da, aynı review disiplini altında değişmesini sağlar, yani aynı değişiklik biriminin parçası haline getirir. Ayrıca dokümantasyonun kod gibi diff'lenebilir olması, kim ne zaman neyi neden değiştirdi sorusuna Git tarihi üzerinden cevap verilmesini sağlar; bu, wiki'lerin genellikle sunamadığı bir izlenebilirlik katmanıdır. İki sistemi aynı anda tutmak ise 'hangisi güncel' belirsizliği yaratır.",
"kaynak": "", "alan": ""},

{"soru": "Bir runbook'ta hangi bölümler mutlaka bulunmalı ve bunların eksikliği ne gibi sorunlara yol açar?",
"cevap": "İyi bir runbook şu bölümleri içermelidir: tetikleyici (bu runbook ne zaman kullanılır, hangi alarm veya belirti prosedürü başlatır), ön koşullar ve yetkiler (hangi erişim ve araç gerekli), adım adım işlemler (belirsizlik bırakmayan, gerçek ortamda test edilmiş kopyala-yapıştır komutlar), doğrulama adımları (her adımdan sonra başarılı olup olmadığının nasıl anlaşılacağı), geri alma (rollback) planı, eskalasyon yolu (runbook yetersiz kalırsa kime ulaşılacağı) ve son güncelleme/test kaydı. Bu bölümlerden herhangi biri eksik olursa ciddi riskler doğar: doğrulama adımı yoksa nöbetçi mühendis bir adımın işe yarayıp yaramadığını bilemez; rollback planı yoksa bir şey ters gittiğinde eski duruma dönüş mümkün olmaz; 'neden' ve 'risk' bilgisi atlanırsa (örneğin bir servisi yeniden başlatmanın açık bağlantıları keseceği belirtilmezse) nöbetçi riski göze alıp almayacağını değerlendiremez. Ayrıca runbook, sistemi kuran kişi için barız olan adımların ilk kez müdahale eden biri için barız olmadığı varsayımıyla, yani hiçbir bağlam bilgisi olmayan yetkin bir mühendis varsayımıyla yazılmalıdır.",
"kaynak": "", "alan": ""},

{"soru": "Eskimiş bir runbook neden hiç runbook olmamasından daha tehlikeli olabilir?",
"cevap": "Sistem zamanla değişir; yeni bir servis eklenir, bir port değişir veya bir komut kaldırılır. Runbook bu değişikliklere paralel güncellenmezse, içeriğinde artık geçersiz varsayımlar ve çalışmayan komutlar birikir. Sorun şudur: eskimiş bir runbook, hala güvenilir görünür ve nöbetçi mühendise sahte bir güven verir. Kriz anındaki stres altında (tunnel vision, panik) mühendis runbook'a körükörüne güvenip yanlış talimatı uygulayabilir; bu, hiç runbook olmayıp mühendisin durumu sıfırdan, dikkatle değerlendirmesinden daha kötü bir sonuç doğurabilir çünkü yanlış güven, eleştirel düşünmeyi devre dışı bırakır. Bu yüzden runbook'lar düzenli olarak tatbikat (game day / fire drill) ile test edilmeli ve olay sonrası incelemelerde (postmortem) runbook'un eksik veya yanlış yönlendirdiği noktalar tespit edilip geri işlenmelidir. Böylece runbook, statik bir belge değil, sürekli doğrulanan yaşayan bir artefakt haline gelir. Ayrıca kritik runbook'lar, olaya neden olan sistemin üzerinde barınmamalı, bağımsız ve yedekli bir kanaldan erişilebilir olmalıdır; aksi halde tam ihtiyaç duyulan anda runbook'un kendisine erişilemeyebilir.",
"kaynak": "", "alan": ""},

{"soru": "ADR, otomatik API dokümantasyonu, docs-as-code ve runbook standartlarının ortak paydası nedir?",
"cevap": "Bu dört pratik, yüzeyde farklı belge türleri gibi görünse de aynı temel mühendislik ilkesinden beslenir: bilgiyi güvenilmez ve ölçeklenmeyen insan hafızasından veya disiplininden çıkarıp sistematik, doğrulanabilir, sürüm kontrollü bir sürece taşımak. ADR, kararların neden alındığını kalıcı hale getirir; otomatik API üretimi, arayüzün kodla senkron kalmasını garanti eder; docs-as-code, tüm dokümantasyonun kodla aynı yaşam döngüsüne (review, versiyon, CI) girmesini sağlar; runbook'lar ise operasyonel bilgiyi kriz anında güvenilir şekilde erişilebilir kılar. Bir organizasyonun dokümantasyon olgunluğunu değerlendirmenin pratik yolu şu soruyu sormaktır: 'Bu bilgi, onu yazan kişi yarın işe gelmese hala doğru ve erişilebilir olur muydu?' Cevap hayırsa, o bilgi hala bir kişinin kafasında yaşıyor demektir ve bu, bilgi silosu (knowledge silo) ile bus factor riskinin somut göstergesidir. Bu dört pratik, bireysel hafızaya bağımlılığı azaltıp bilgiyi sistemin, sürecin ve deponun bir parçası haline getirerek organizasyonel dayanıklılığı artırır.",
"kaynak": "", "alan": ""},
]

# Preserve original kaynak/alan values (they were empty/absent in source; source lines had no kaynak/alan)
# Actually source lines only had soru and cevap. Keep only those keys present in source.
out_path = str(KOK / "data" / "processed" / "instruct_tr" / "yazilim_dokumantasyon-muhendisligi.jsonl")
with open(out_path, "w", encoding="utf-8") as f:
    for r in rows:
        obj = {"soru": r["soru"], "cevap": r["cevap"]}
        f.write(json.dumps(obj, ensure_ascii=False) + "\n")
print("done", len(rows))
