from pathlib import Path
import json

# Depo koku - kisisel makine yolu yerine bu dosyanin konumundan turetilir.
KOK = Path(__file__).resolve().parents[1]

items = [
("Dağıtık sistemlerde kısmi hata (partial failure) nedir ve tek makineli sistemlerden farkı ne?",
"Kısmi hata, bir dağıtık sistemin bazı bileşenleri çökerken diğer bileşenlerin sağlıklı çalışmaya devam etmesi durumudur. Tek bir makinede program ya tamamen çalışır ya da tamamen çöker; ara bir durum yoktur. Dağıtık sistemde ise sistemin bir bölümü çökebilirken diğer bölümü hiçbir sorun yaşamadan işlemeye devam edebilir. Bunun asıl zorluğu, çalışan tarafın çöken tarafın gerçekten çöktüğünü hemen ve kesin olarak anlayamamasıdır: bir node'a istek gönderip yanıt alamadığınızda, o node'un çökmüş mü olduğunu, sadece yavaş mı yanıt verdiğini, isteğin ağda mı kaybolduğunu, yoksa isteği işleyip yanıtı gönderirken mi kaybettiğini dışarıdan ayırt edemezsiniz. Elinizdeki tek işaret sessizliktir ve bu sessizlik tüm bu senaryoların ortak sonucudur. Bu yüzden dağıtık sistemlerde hata tespiti kesinlik değil şüphe üretir; pratikte \"şu kadar süredir cevap yok, o hâlde ölü sayıyorum\" denir, \"biliyorum\" denmez. Bu belirsizlik, timeout seçimi, quorum mantığı ve retry stratejileri gibi pek çok tasarım kararının kök nedenidir."),

("Neden dağıtık sistemlerde olayları sıralamak için doğrudan duvar saati (wall clock) zaman damgaları kullanılmaz?",
"Çünkü farklı makinelerin saatleri birbirinden bağımsız kayar (clock drift) ve NTP gibi senkronizasyon protokolleri sıfır fark garantisi vermez, hatta saati bazen geriye bile ayarlayabilir. Örneğin node A bir olaya t=100 zaman damgası koyarken, node B'nin saati geride olduğu için gerçekte sonra gerçekleşen bir olayına t=95 gibi daha küçük bir damga koyabilir. Zaman damgalarına körü körüne güvenip küçük olanın önce olduğunu varsaymak nedenselliği ihlal eder. Ayrıca saatin geriye gidebilmesi, \"iki now() çağrısı arasındaki fark her zaman pozitiftir\" varsayımına dayanan kodları bozar; bu yüzden süre ölçümü asla duvar saatiyle yapılmamalıdır. Doğru pratik, süre ölçmek için yalnızca ileri giden monotonik saati, bir anı insan diline çevirmek (loglama, son kullanma tarihi gibi) için ise duvar saatini kullanmaktır. Olaylar arasında nedensellik veya sıralama kurmak gerektiğinde ise fiziksel zamandan tamamen vazgeçilip Lamport saati veya vektör saati gibi mantıksal saatlere başvurulur, çünkü asıl önemli olan \"kaçta olduğu\" değil \"hangi olayın hangisinden önce gelebileceği\"dir."),

("Lamport saati ile vektör saati arasındaki fark nedir, hangi durumda vektör saatine ihtiyaç duyulur?",
"Lamport saati basit bir sayaçtır: her node kendi sayacını tutar, bir olay olduğunda artırır, mesaj gönderirken sayaç değerini iliştirir, mesaj alırken kendi sayacını max(kendi sayaç, gelen sayaç)+1 yapar. Bu sayede eğer A olayı gerçekten B olayının nedeniyse, A'nın Lamport zamanı B'ninkinden küçük çıkar; yani Lamport saati nedenselliği korur. Ancak tersi geçerli değildir: Lamport zamanı küçük olan bir olay illa nedensel olarak önce gelmiş olmak zorunda değildir, birbirinden habersiz (concurrent) iki olay da olabilir. Lamport saati bu ayrımı yapamaz. Vektör saati ise her node'un tüm node'ların sayaçlarından oluşan bir vektör tutmasıyla çalışır; iki vektör karşılaştırıldığında \"A kesinlikle B'den önce oldu\", \"B kesinlikle A'dan önce oldu\" veya \"bunlar eşzamanlı, birbirinden bağımsız\" sonuçlarından hangisinin doğru olduğu tam olarak belirlenebilir. Bedeli, node sayısıyla birlikte büyüyen bir vektör taşımaktır. Vektör saatleri özellikle birden fazla node'un aynı anahtara aynı anda farklı değerler yazdığı çakışma (conflict) durumlarını tespit etmek için kullanılır."),

("Split-brain nedir ve quorum mantığı buna karşı nasıl koruma sağlar?",
"Split-brain, bir ağ bölünmesinin (network partition) kümeyi iki gruba ayırması ve her iki grubun da diğerini ölmüş sanarak kendini lider ilan etmesi durumudur. Sonuçta iki lider aynı anda birbiriyle çelişen kararlar alabilir; örneğin bir banka bakiyesi iki farklı tarafta iki farklı şekilde güncellenebilir ve ağ tekrar birleştiğinde bu iki gerçek uzlaştırılamaz. Buna karşı temel savunma quorum, yani çoğunluk mantığıdır: bir karar ancak node'ların çoğunluğu onayladığında geçerli sayılır. Örneğin beş node'luk bir kümede karar için en az üç onay gerekir. Ağ 2'ye 3 şeklinde bölündüğünde, üç node'luk taraf çoğunluğu sağladığı için çalışmaya devam eder, iki node'luk taraf ise çoğunluğu sağlayamadığı için kendini durdurur. İki tarafın da aynı anda çoğunluk olması matematiksel olarak imkânsız olduğundan iki lider birden var olamaz. Quorum split-brain'in oluşumunu değil, iki tarafın aynı anda yazma yapmasını imkânsız kılar; bu da yeterlidir. Bu yüzden küme boyutları genellikle tek sayı (3, 5, 7) seçilir, çünkü çift sayıda node'la tam ortadan bölünme çoğunluğu belirsizleştirebilir."),

("Raft consensus algoritmasının temel mekanizmaları nelerdir ve quorum ile bağlantısı nasıl kurulur?",
"Raft, koordinasyonu tek bir lidere yıkarak consensus problemini sadeleştirir ve üç mekanizmadan oluşur. Lider seçimi (leader election): node'lar başlangıçta takipçidir; belirli bir süre liderden haber alamayan bir node aday olur ve oy ister, çoğunluğun oyunu alan node lider olur. Her seçim bir terim (term) numarasıyla etiketlenir; bu numara mantıksal bir saat gibi davranarak eski bir liderin geri dönüp karışıklık çıkarmasını engeller, çünkü daha büyük terimli mesaj her zaman kazanır. Log replikasyonu: tüm yazmalar liderden geçer, lider kaydı takipçilere gönderir ve çoğunluk kaydı diske yazdığını onaylayınca kayıt \"commit\" edilmiş sayılır. Güvenlik kuralı: yalnızca en güncel loga sahip node lider olabilir; bu, commit edilmiş bir kaydın asla kaybolmamasını garanti eder. Buradaki quorum bağlantısı kritiktir: bir kayıt çoğunluk tarafından yazıldığında commit sayıldığından ve yeni lider olmak da çoğunluk oyu gerektirdiğinden, herhangi iki çoğunluk kümesi matematiksel olarak en az bir ortak node'da kesişmek zorundadır. O ortak node commit edilmiş kaydı taşıdığı için yeni lider onu görmek zorunda kalır ve kayıt asla kaybolmaz. Consensus'un tüm güvenliği bu kesişim özelliğine dayanır."),

("Idempotency nedir ve bir işlemi idempotent yapmak için idempotency anahtarı nasıl doğru kullanılır?",
"Bir işlem idempotent ise, onu bir kez de beş kez de çalıştırsanız sistemin son durumu aynı kalır. Örneğin \"bakiyeyi 100 yap\" idempotenttir, kaç kez uygulanırsa uygulansın bakiye 100 olur; ama \"bakiyeye 100 ekle\" idempotent değildir çünkü tekrarlandıkça bakiye şişer. Idempotency merkezi bir kavramdır çünkü güvenilmez ağda bir istek gönderip yanıt alamadığınızda isteğin işlenip işlenmediğini bilemezsiniz ve elinizdeki tek makul seçenek yeniden denemektir (retry); retry ise ancak işlem idempotent ise güvenlidir. En yaygın yöntem idempotency anahtarı kullanmaktır: istemci her isteğe benzersiz bir kimlik (genellikle UUID) iliştirir, sunucu işlemeden önce bu anahtarı bir kayıt tablosunda arar; anahtar daha önce görülmüşse işlemi tekrar çalıştırmaz, sadece ilk seferki yanıtı geri döner, görülmemişse işlemi çalıştırıp sonucu anahtarla birlikte kaydeder. Kritik nokta, anahtarın kontrolü, işin yapılması ve sonucun kaydedilmesinin atomik olmasıdır; aksi hâlde iki eşzamanlı retry ikisi de \"bu anahtarı görmedim\" deyip işi iki kez çalıştırabilir. Bu atomiklik genellikle veritabanının benzersizlik kısıtı veya transaction mekanizmasıyla sağlanır."),

("Idempotency uygularken en yaygın tuzaklar nelerdir?",
"En sinsi tuzak yan etkileri (side effect) unutmaktır: ana veritabanı yazması idempotent olsa bile, aynı işlem bir e-posta veya bildirim gönderiyorsa, retry ikinci bir e-posta yollayabilir. Idempotency, işlemin sadece veritabanı kısmı için değil, dış dünyaya olan tüm etkileri kapsayacak şekilde tasarlanmalıdır. İkinci tuzak, idempotency kayıtlarının süresiz saklanmasıdır; anahtar tablosu sonsuza dek büyürse depolama sorunu oluşur, bu yüzden anahtarlara makul bir yaşam süresi (TTL) verilir, ancak bu süre olası retry penceresinden mutlaka uzun olmalıdır, yoksa anahtar silindikten sonra gelen bir retry işlemi tekrar çalıştırabilir. Üçüncü tuzak kısmi başarıdır: bir işlem ortasına kadar ilerleyip çökerse, retry'ın tutarlı bir noktadan devam edebilmesi için işin kendisinin de idempotent adımlardan oluşması gerekir; aksi hâlde kısmi olarak tamamlanmış bir işlemin üzerine tekrar yazmak tutarsız bir duruma yol açabilir."),

("Saf exactly-once teslimat neden imkânsıza yakındır ve sistemler pratikte \"exactly-once\" derken gerçekte ne yapar?",
"Mesaj teslimatında saf exactly-once fiziksel olarak imkânsıza yakındır çünkü kök nedeni yine ayırt edilemezliktir: gönderen bir mesaj yollar, alan işler ve onay (ack) döner, ama ack yolda kaybolabilir; gönderen ack'i görmediği için mesajı yeniden gönderir ve alan mesajı ikinci kez alabilir. Gönderen \"tekrar göndermeme\" ile \"tekrar gönderme\" arasında seçim yapmak zorundadır ve her iki seçim de ya kayba ya duplicate'e yol açar; kaybı önlemek zorunda olduğu için ağ katmanı en fazla at-least-once (en az bir kez) garantisi verebilir. Bu imkânsızlığın teorik kökeni İki Ordu Problemi'dir: güvenilmez bir kanal üzerinden iki tarafın bir eylem üzerinde kesin ortak bilgiye ulaşması mümkün değildir. Bu yüzden \"exactly-once destekliyoruz\" diyen sistemler aslında teslimatı at-least-once bırakır ama işlemenin etkisini tam bir kez olacak şekilde tasarlar (effectively-once). Bunu sağlayan iki temel teknik vardır: idempotent tüketici (mesajın kimliğini kaydedip aynı kimliği ikinci görüşte atlamak) ve atomik commit / transactional outbox (mesajı işleme ile \"işledim\" işaretini aynı transaction içinde atomik olarak koymak). Yani exactly-once, at-least-once teslimat artı idempotent işlemenin birleşiminden doğan bir sonuçtur, ayrı bir sihir değildir."),

("Bir sistemde consensus mekanizması her karar için mi kullanılmalı, yoksa sınırlı mı tutulmalı? Neden?",
"Consensus sınırlı tutulmalıdır, her karar için kullanılmamalıdır. Consensus ucuz değildir; her karar için birden çok tur mesajlaşma ve disk yazımı gerektirir ve bu da ciddi gecikme ekler. Bu yüzden doğru pratik, consensus'u yalnızca gerçekten global anlaşma gerektiren kritik metadata için kullanmaktır: lider kimliği, konfigürasyon, kilit sahipliği, shard atamaları gibi. Yüksek hacimli asıl veri yolu ise mümkün olduğunca consensus dışında tutulmalıdır. Yaygın ve sağlıklı mimari, küçük ve kritik durumu bir consensus servisine (Raft veya Paxos temelli bir koordinasyon servisi) emanet edip, asıl iş yükünün bu servisin verdiği kararlara dayanmasıdır. Ayrıca kendi consensus algoritmanızı sıfırdan yazmaya kalkmak da önerilmez; bu, doğru yapılması yıllar alan ve küçük bir hatanın sessizce veri kaybına yol açabildiği bir alandır. Bunun yerine olgunlaşmış, kanıtlanmış Raft veya Paxos temelli mekanizmalar tercih edilmelidir."),
]

path = str(KOK / "data" / "processed" / "instruct_tr" / "yazilim_dagitik-sistemler.jsonl")
with open(path, "w", encoding="utf-8") as f:
    for soru, cevap in items:
        obj = {"soru": soru, "cevap": cevap, "kaynak": "dagitik-sistemler", "alan": "yazilim"}
        f.write(json.dumps(obj, ensure_ascii=False) + "\n")

print("wrote", len(items))
