import json

items = [
{
"soru": "Bit manipulasyonu nedir ve neden sadece bir mikro-optimizasyon numarasi olarak gorulmemeli?",
"cevap": "Bit manipulasyonu, bir sayinin ikili (binary) gosterimindeki tek tek bitleri okuma, set etme, temizleme ve cevirme islemlerinin tumudur. Islemciler veriyi 8, 16, 32 veya 64 bitlik kelimeler halinde tutar ve bu bitlerin her biri bir bellek hucresindeki mantiksal 0 ya da 1 durumunu temsil eder. Bu teknigin onemi yalnizca hiz kazanmakla sinirli degildir; isletim sistemi cekirdekleri, network protokolleri, dosya sistemleri, sikistirma algoritmalari, kriptografi, grafik motorlari ve gomulu sistemler dogalari geregi bit seviyesinde calisir. Ornegin bir TCP basligindaki flag'ler, bir dosya izin maskesi, bir renk kanalinin paketlenmesi ya da bir donanim register'inin kontrol bitleri hep bit manipulasyonuyla ele alinir. Dolayisiyla bu, sistem programciliginin temel dilidir ve yalnizca performans icin degil, donanimla ve protokollerle dogru sekilde iletisim kurabilmek icin de gereklidir. Yuksek seviyeli soyutlamalarin (boolean dizisi, set gibi) getirdigi bellek ve hiz maliyetinden kacinmak isteyen her sistem programcisinin bilmesi gereken temel bir beceridir."
},
{
"soru": "64 tane boolean bayragi ayri ayri tutmak yerine bunlari bitlere paketlemek neden bu kadar buyuk bellek kazanci saglar?",
"cevap": "Cogu programlama dilinde tek bir bool degeri, aslinda yalnizca 1 bit bilgi tasimasina ragmen 1 byte (8 bit) yer kaplar; cunku islemciler byte'tan daha kucuk adreslenebilir birimlerle verimli calisamaz. Dolayisiyla 64 boolean bayragi ayri ayri degiskenler olarak tutuldugunda toplam 64 byte harcanir. Oysa bu 64 bayragi tek bir 64 bitlik tamsayinin bitlerine yerlestirirseniz yalnizca 8 byte yeterli olur; bu sekiz kat bellek kazanci demektir. Milyonlarca nesne icin bu fark, verinin CPU cache'ine sigip sigmamasi arasindaki farki belirler ve cache'e sigan veri, ana bellege gitmek zorunda kalan veriden cok daha hizli islenir. Bu yuzden bit paketleme sadece az yer kaplama degil, ayni zamanda dolayli olarak buyuk bir hiz kazanci da saglar; cunku modern islemcilerde bellek erisimi aritmetik islemlerden kat kat yavastir ve cache lokalitesi performansin asil belirleyicisidir."
},
{
"soru": "AND, OR ve XOR operatorleri bit set etme, temizleme ve cevirme islemlerinde neden birbirinin yerine kullanilamaz?",
"cevap": "Bu uc operatorun farkli mantiksal davranislari, onlari farkli gorevler icin ozel kilar. AND operatorunde iki bit de 1 ise sonuc 1'dir; bu yuzden bir biti 0 ile AND'lerseniz sonuc her zaman 0 olur, 1 ile AND'lerseniz bit kendi degerini korur. Bu ozellik AND'i bir filtre yapar ve bit okumak ile temizlemek icin idealdir. OR operatorunde bitlerden en az biri 1 ise sonuc 1'dir; 1 ile OR her zaman 1 verir, 0 ile OR ise degeri degistirmeden korur, bu yuzden bit set etmek (acmak) icin kullanilir. XOR operatorunde bitler farkliysa sonuc 1'dir; 1 ile XOR biti tersine cevirir, 0 ile XOR ise korur, bu yuzden toggle (cevirme) islemi icin uygundur. Ayrica XOR'un kendisiyle islemi sifir vermesi (a XOR a = 0) ve tersinir olmasi, degisken takasi, checksum hesaplama ve tek kalan elemani bulma gibi bircok klasik hilenin temelini olusturur. Ozetle her operatorun 0 ve 1 ile etkilesimindeki asimetri, onu belirli bir bit islemine ozgu kilar."
},
{
"soru": "Belirli bir biti set etmek, temizlemek, cevirmek ve okumak icin kullanilan standart maskeleme kaliplari nasil calisir?",
"cevap": "Bir pos konumundaki biti set etmek icin x |= (1u << pos) yazilir: 1u << pos ifadesi yalnizca pos konumunda 1 olan bir maske uretir ve bu maske OR'landiginda sadece o bit acilir, digerleri etkilenmez. Temizlemek icin x &= ~(1u << pos) kullanilir: maske tersine cevrilince pos haric her yer 1 olur ve bununla AND yapildiginda pos biti 0'a zorlanirken diger bitler korunur. Cevirmek (toggle) icin x ^= (1u << pos) kullanilir; cunku XOR, maskedeki 1'lerin denk geldigi bitleri tersine cevirir, geri kalani degistirmez. Okumak icin ise bit = (x >> pos) & 1u yazilir: once ilgilenilen bit en saga kaydirilir, ardindan & 1 ile izole edilir. Cok bitlik bir alani (ornegin 8-15. bitleri) okumak icin once kaydirma sonra maskeleme yapilir: (x >> 8) & 0xFF gibi. Bir alani yazmak ise iki adimlidir: once eski deger temizlenir, sonra yenisi yerlestirilir; bu clear-then-set kalibi, ozellikle donanim register'larina yazarken kritik onemdedir cunku temizleme adimi atlanirsa eski bitler yeniyle OR'lanip cop deger olusur."
},
{
"soru": "x & (x-1) ifadesi bir sayinin en dusuk set bitini neden temizler?",
"cevap": "Bir sayidan 1 cikarildiginda, ikili aritmetigin dogasi geregi en sagdaki 1 biti 0'a doner ve ondan sonraki (sagindaki) tum 0'lar 1'e cevrilir. Ornegin x = 10110000 ise x-1 = 10101111 olur: en sagdaki 1 (dorduncu bitteki) 0'a donmus, ondan sagdaki uc 0 ise 1'e donmustur. Bu iki degeri AND'lediginizde, ortak olmayan alt kisim (degisen bitler) elenir ve yalnizca 10100000 kalir; yani en dusuk set bit tamamen silinmistir. Bu bir tesaduf degil, dogrudan ikili cikarma isleminin mekanik sonucudur. Bu hile pratikte onemlidir cunku bir sayidaki toplam set bit sayisini saymak (Brian Kernighan yontemi) icin kullanilir: dongu her adimda x & (x-1) uygular ve x sifir olana kadar devam eder. Bu yaklasimin avantaji, dongunun sayidaki bit genisligi kadar degil (ornegin 32 kez), yalnizca set bit sayisi kadar donmesidir; yani seyrek (az sayida 1 iceren) sayilarda cok daha hizlidir."
},
{
"soru": "if (x & MASK == 0) yazan bir kod neden cogu zaman beklenmedik sekilde calisir ve dogrusu nasil yazilmalidir?",
"cevap": "Bunun sebebi C ailesi dillerde operator onceligidir: bit operatorlerinin (& gibi) onceligi, karsilastirma operatorlerinden (== gibi) daha dusuktur. Bu yuzden if (x & MASK == 0) ifadesinde derleyici once MASK == 0 karsilastirmasini degerlendirir (bu genellikle false, yani 0 sonucu verir), ardindan x & 0 islemini yapar; bu da her zaman 0 sonucunu uretir ve kosul her durumda ayni (genellikle yanlis) sekilde degerlendirilir, sizin bekledigi 'x'in MASK ile kesisimi sifir mi' sorusuna hic cevap vermez. Bu, C ailesinde en sinsi ve en sik rastlanan bit hatalarindan biridir cunku kod derlenir, calisir, ama yanlis sonuc uretir; hata cogu zaman fark edilmez. Dogru yazim if ((x & MASK) == 0) seklinde, bit islemini parantez icine alarak once onun degerlendirilmesini garanti etmektir. Bu tur hatalardan kacinmanin en guvenilir yolu, bit operatorleri her karsilastirmayla bir arada kullanildiginda aliskanlik haline getirilmis parantez kullanimidir."
},
{
"soru": "Bit manipulasyonunda isaretli (signed) tamsayilar yerine isaretsiz (unsigned) tipler kullanmak neden onerilir?",
"cevap": "Isaretli tamsayilarla kaydirma yapmak, bircok dilde tanimsiz veya uygulamaya bagli davranisa (undefined/implementation-defined behavior) cok yakin calisir. Ornegin C/C++'ta 1 << 31 ifadesi, isaretli 32 bitlik bir int uzerinde isaret bitine tasma sayilir ve bu tanimsiz davranistir; derleyici bu durumu optimizasyon sirasinda istismar edebilir, yani kodun davranisi ongorulemez hale gelir. Ayrica isaretli sayilarda sag kaydirmanin iki turu vardir: mantiksal kaydirma soldan 0 doldururken, aritmetik kaydirma isaret bitini korur; negatif sayilarin dogru bolunmesi icin aritmetik kaydirma gerekir ama bazi dillerde hangi turun kullanilacagi uygulamaya baglidir, bu da tasinabilirlik sorunu yaratir. Bu belirsizliklerden kacinmanin yolu, bit manipulasyonu yapilan yerlerde maske sabitlerini isaretsiz yazmaktir: 1u << 31 ya da 64 bit icin 1ull << 63 gibi. Genel kural nettir: bit manipulasyonu yapiyorsaniz isaretsiz tipler (uint32_t, uint64_t gibi sabit genislikli tipler) kullanin; isaret biti isleri hizla karistirir ve platformlar arasi ongorulemez sonuclara yol acar."
},
{
"soru": "Bir bitset kullanmanin kume (set) islemlerinde siradan bir diziye veya boolean listesine gore performans avantaji nereden gelir?",
"cevap": "Bitset, cok sayida boolean degeri bir tamsayi dizisinin bitlerine paketleyerek tutan bir veri yapisidir; N elemanli bir kume icin N bit ayrilir ve her bit bir elemanin var/yok durumunu temsil eder. Bitset'in gucu, kesisim (AND), birlesim (OR), fark (AND NOT) ve simetrik fark (XOR) gibi kume operasyonlarinin kelime kelime (ornegin 64 bit birden) yurutulebilmesinden gelir; cunku islemci bu bit operasyonlarini bir kelimenin tum bitleri uzerinde tek bir makine komutuyla ayni anda uygular. Ornegin 64 bitlik bir platformda 640 elemanli iki kumenin kesisimini almak yalnizca 10 kelime islemi gerektirir; elemanlari teker teker karsilastirmaya kiyasla 64 kat daha az is demektir. Bu yaklasimin gercek dunyadaki en yaygin kullanimi veritabani ve arama motorlarindaki bitmap index'lerdir: milyonlarca kaydin belirli bir ozelligi tasiyip tasimadigi bir bitmap'te tutulur ve birden fazla kosulu saglayan kayitlari bulmak, ilgili bitmap'lerin AND'lenmesiyle cok hizli cozulur. Seyrek veriler icin ise Roaring Bitmap gibi sikistirilmis bitmap yapilari hem bellek hem hiz avantajini bir arada korur."
},
{
"soru": "Bit hileleriyle yazilmis akilli kod her zaman performans acisindan tercih edilmeli midir, yoksa ne zaman kacinilmalidir?",
"cevap": "Hayir, bit hileleri her yerde otomatik bir kazanc saglamaz ve bazi durumlarda zarar bile verebilir. En buyuk gercek kazanc genellikle hizli komut kullanmaktan degil, verinin daha az yer kaplayip CPU cache'ine sigmasindan gelir; cunku ana bellege erisim, aritmetik islemlerden kat kat yavastir. Bunun disinda birkac tuzak vardir: Birincisi erken optimizasyondur, sicak yol (hot path) olmayan bir yerde kodu bit hileleriyle sifreleyip okunmaz hale getirmenin kazandirdigi nanosaniyeler buna degmez; ayrica derleyiciler zaten x % 2 veya x / 8 gibi ifadeleri kendiliginden bit operasyonlarina cevirir. Ikincisi dallanma (branch) maliyetidir; dalsiz (branchless) bit hileleri yalnizca dal tahmininin gercekten basarisiz oldugu ongorulemez durumlarda kazandirir, cunku modern islemcilerin dal tahmini genelde cok basarilidir ve bunu ancak profil olcumu soyleyebilir. Ucuncusu tasinabilirlik sorunudur; __builtin_popcount gibi derleyiciye ozgu intrinsic'ler hedef platformda karsilik bulamazsa yavas bir yazilim karsiligina dusebilir. Genel ilke nettir: once ol, sonra optimize et; bit manipulasyonunu yalnizca profiler'in isaret ettigi olculebilir kazanc olan sicak noktalarda kullanin."
},
]

path = r"C:\Users\yilma\Desktop\yeni bir jarvis\data\processed\instruct_tr\yazilim_bit-manipulasyonu.jsonl"
with open(path, "w", encoding="utf-8") as f:
    for it in items:
        obj = {"soru": it["soru"], "cevap": it["cevap"], "kaynak": "bit-manipulasyonu", "alan": "yazilim"}
        f.write(json.dumps(obj, ensure_ascii=False) + "\n")

print(len(items))
